//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace poco2swift {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("poco2swift", Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd", IsNullable=false)]
    public partial class Poco2SwiftType {
        
        private ModuleType[] importsField;
        
        private SkipType[] skiptypesField;
        
        private ExternalType[] externaltypesField;
        
        private EnumType[] enumerationsField;
        
        private ClassType[] classesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("module", IsNullable=false)]
        public ModuleType[] imports {
            get {
                return this.importsField;
            }
            set {
                this.importsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("skip-types")]
        [System.Xml.Serialization.XmlArrayItemAttribute("skip-type", IsNullable=false)]
        public SkipType[] skiptypes {
            get {
                return this.skiptypesField;
            }
            set {
                this.skiptypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("external-types")]
        [System.Xml.Serialization.XmlArrayItemAttribute("external-type", IsNullable=false)]
        public ExternalType[] externaltypes {
            get {
                return this.externaltypesField;
            }
            set {
                this.externaltypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("enum", IsNullable=false)]
        public EnumType[] enumerations {
            get {
                return this.enumerationsField;
            }
            set {
                this.enumerationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("class", IsNullable=false)]
        public ClassType[] classes {
            get {
                return this.classesField;
            }
            set {
                this.classesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    public partial class ModuleType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    public partial class PropertyType {
        
        private string nameField;
        
        private bool skipField;
        
        private bool skipFieldSpecified;
        
        private string swiftnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool skip {
            get {
                return this.skipField;
            }
            set {
                this.skipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skipSpecified {
            get {
                return this.skipFieldSpecified;
            }
            set {
                this.skipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("swift-name")]
        public string swiftname {
            get {
                return this.swiftnameField;
            }
            set {
                this.swiftnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    public partial class EnumValueType {
        
        private string nameField;
        
        private bool skipField;
        
        private bool skipFieldSpecified;
        
        private string swiftnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool skip {
            get {
                return this.skipField;
            }
            set {
                this.skipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skipSpecified {
            get {
                return this.skipFieldSpecified;
            }
            set {
                this.skipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("swift-name")]
        public string swiftname {
            get {
                return this.swiftnameField;
            }
            set {
                this.swiftnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    public partial class TypeType {
        
        private string nameField;
        
        private bool forceincludeField;
        
        private string fullnameField;
        
        private string swiftnameField;
        
        public TypeType() {
            this.forceincludeField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("force-include")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool forceinclude {
            get {
                return this.forceincludeField;
            }
            set {
                this.forceincludeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("full-name")]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("swift-name")]
        public string swiftname {
            get {
                return this.swiftnameField;
            }
            set {
                this.swiftnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    public partial class ClassType : TypeType {
        
        private PropertyType[] propertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public PropertyType[] property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    public partial class EnumType : TypeType {
        
        private EnumValueType[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public EnumValueType[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    public partial class ExternalType {
        
        private string fullnameField;
        
        private string swiftnameField;
        
        private bool isvaluetypeField;
        
        public ExternalType() {
            this.isvaluetypeField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("full-name")]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("swift-name")]
        public string swiftname {
            get {
                return this.swiftnameField;
            }
            set {
                this.swiftnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("is-value-type")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isvaluetype {
            get {
                return this.isvaluetypeField;
            }
            set {
                this.isvaluetypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://paullalonde.ca/schemas/pod2swift/Configuration.xsd")]
    public partial class SkipType {
        
        private string fullnameField;
        
        private string matchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("full-name")]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string match {
            get {
                return this.matchField;
            }
            set {
                this.matchField = value;
            }
        }
    }
}
